# permissions for end users to edit commands.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: command-editor-role
rules:
- apiGroups:
  - bus.volcano.sh
  resources:
  - commands
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bus.volcano.sh
  resources:
  - commands/status
  verbs:
  - get
