# permissions for end users to view commands.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: command-viewer-role
rules:
- apiGroups:
  - bus.hvolcano.sh
  resources:
  - commands
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bus.hvolcano.sh
  resources:
  - commands/status
  verbs:
  - get
