# permissions for end users to view podgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podgroup-viewer-role
rules:
- apiGroups:
  - scheduling.hliangzhao.io
  resources:
  - podgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.hliangzhao.io
  resources:
  - podgroups/status
  verbs:
  - get
