# this config file is used to build a kind cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 4 worker nodes
nodes:
  # the control plane node config
  - role: control-plane
  # the four workers
  - role: worker
  - role: worker
  - role: worker
  - role: worker
